# Generated by Django 6.0.6 on 2026-06-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherreport',
            options={'verbose_name': 'Прогноз погоди', 'verbose_name_plural': 'Прогнози погоди'},
        ),
        migrations.RemoveField(
            model_name='weatherreport',
            name='date_parsed',
        ),
        migrations.RemoveField(
            model_name='weatherreport',
            name='temperature',
        ),
        migrations.AddField(
            model_name='city',
            name='is_monitored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='url_name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='URL-назва'),
        ),
        migrations.AddField(
            model_name='weatherreport',
            name='max_temp',
            field=models.IntegerField(null=True, verbose_name='Макс. температура'),
        ),
        migrations.AddField(
            model_name='weatherreport',
            name='min_temp',
            field=models.IntegerField(null=True, verbose_name='Мін. температура'),
        ),
        migrations.AddField(
            model_name='weatherreport',
            name='parsed_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Час парсингу'),
        ),
        migrations.AddField(
            model_name='weatherreport',
            name='target_date',
            field=models.DateField(null=True, verbose_name='Дата прогнозу'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Назва міста'),
        ),
    ]
