# Generated by Django 6.0.6 on 2026-06-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_weatherreport_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weatherreport',
            unique_together={('city', 'source', 'target_date')},
        ),
    ]
