# Generated by Django 6.0.6 on 2026-06-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_weatherreport_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherreport',
            name='condition',
            field=models.CharField(choices=[('clear', 'Ясно'), ('clear_night', 'Ясно, ніч'), ('little_clouds', 'Малохмарно'), ('clouds', 'Хмарно'), ('clouds_night', 'Хмарно, ніч'), ('gloom', 'Похмуро'), ('little_rain', 'Невеликий дощ'), ('rain', 'Дощ'), ('sunny_rain', 'Дощ з сонцем'), ('snow', 'Сніг'), ('light_snow', 'Невеликий сніг'), ('snow_and_rain', 'Сніг з дощем'), ('storm', 'Гроза'), ('hailstorm', 'Град')], max_length=20, null=True, verbose_name='Стан погоди'),
        ),
    ]
