# Generated by Django 6.0.6 on 2026-07-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_weatherreport_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherreport',
            name='parsed_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Час парсингу'),
        ),
    ]
