# Generated by Django 6.0.6 on 2026-07-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_weatherreport_parsed_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weatherreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True, verbose_name='Довгота'),
        ),
        migrations.AddField(
            model_name='weatherreport',
            name='forecast_date',
            field=models.DateField(null=True, verbose_name='Дата створення прогнозу'),
        ),
        migrations.AlterField(
            model_name='weatherreport',
            name='target_date',
            field=models.DateField(null=True, verbose_name='Прогноз на дату'),
        ),
        migrations.AlterUniqueTogether(
            name='weatherreport',
            unique_together={('city', 'source', 'target_date', 'forecast_date')},
        ),
    ]
